services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
    volumes:
      - ./app:/app
    depends_on:
      - db
    profiles: ["api", "test"]
  
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles: ["api", "test"]

  db-test:
    image: postgres:15
    container_name: postgres_test_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    ports:
      - "5431:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    profiles: ["api", "test"]
  
  test:
    build:
      context: .
      dockerfile: /tests/Dockerfile
    container_name: fastapi_test
    command: ["pytest", "/tests/", "--disable-warnings"]
    environment:
      - DATABASE_URL=${TEST_DATABASE_URL}
    volumes:
      - ./app:/app
      - ./tests:/tests
    depends_on:
      - app
    profiles: ["test"]

volumes:
  postgres_data:
